name: rlv2_flutter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.3
  flutter_secure_storage: ^9.2.2
  flutter_stripe: ^11.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  logger: ^2.4.0
  path_provider: ^2.0.11
  riverpod_annotation: ^3.0.0-dev.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/icons/
    - .env